import { ProductRepository } from '../../sequelize/ProductRepository';
import { ProductService } from '../ProductService';
import { Product } from '../../models';

export const productRepository = new ProductRepository();
export const productService = new ProductService(productRepository);

export const products: Product[] = [
  {
    id: 19305,
    agent_id: 103250,
    buyer_id: 5571,
    slug: 'toyota-all-new-grand-innova-v-diesel-24-at-diesel-2021',
    brand_id: 13,
    model_id: 148,
    type_id: 833,
    tahun: 2021,
    jarak_tempuh: 22222,
    nomor_polisi: 'KT8240DEF',
    warna_primer_id: 1,
    warna_sekunder_id: null,
    dokumen_stnk: 'Pribadi',
    dokumen_pajak: 'Hidup',
    dokumen_pajak_tahun_mati: 2022,
    dokumen_pajak_bulan_mati: 7,
    dokumen_bpkb: 'Leasing',
    dokumen_faktur: 'Ada',
    dokumen_nik: 'Ada',
    dokumen_buku_manual: 'Ada',
    dokumen_kunci_serep: 'Ada',
    dokumen_buku_servis: 'Ada',
    harga_jual: 45000000,
    komisi: 0,
    latest_status: 'pembayaran-selesai',
    no_wa_penjual: '088888888',
    bank_code: 'bri',
    bank_name: 'Bank BRI ',
    bank_account_number: '111111',
    bank_account_name: 'BRI Simulator A',
    created_at: new Date(),
    updated_at: new Date(),
    reason: null,
    verified: 1,
    harga_buyout: 45000000,
    hasil_inspeksi:
      '{"user": {"id": 100347, "dob": "1994-09-09", "nik": "3175060909941003", "name": "ASO Warehouse", "role": {"id": 361, "name": "aso", "level": 2, "status": 1, "createdAt": "2021-08-16T07:50:34.000Z", "parent_id": null, "productId": 1, "updatedAt": null, "product_id": 1, "description": "Agent Sales Officer", "all_resource": 0, "originalName": "aso", "original_name": "aso"}, "email": "asowarehouse1@gmail.com", "phone": "8111222333222", "status": 1, "address": "Jakarta Timur", "faso_id": null, "role_id": 361, "isRunner": false, "otp_code": 1234, "password": null, "branch_id": 63, "createdAt": "2020-01-01T12:00:00.000Z", "isOrganic": 0, "join_date": "2020-01-01T12:00:00.000Z", "kycStatus": 2, "parent_id": 100334, "unique_id": "818c66a0-179f-4e60-8ee8-fdeaceaca16c", "updatedAt": "2022-07-01T09:42:54.000Z", "kyc_status": 2, "status_aso": null, "blockBuyout": 0, "company_name": null, "country_code": null, "occupationId": null, "blockWithdraw": 0, "loginRequired": 0, "occupation_id": null, "otp_expiry_at": "2022-07-01T09:47:54.000Z", "referral_code": "ASOW2310", "profile_picture": "https://eu.ui-avatars.com/api/?background=926900&color=fff&size=128&name=ASO+WAREHOUSE", "verifiedAgentAt": null, "otp_resend_count": 0, "companyExperience": null, "id_card_image_url": "https://moladin-evo.s3.ap-southeast-1.amazonaws.com/2022/05/24/1653365840-tangkapan-layar-contoh-e-ktp-yang-sudah-diberi-watermark-fot-hxj6.jpeg", "walletTooltipShown": true, "accountStatementUrl": null, "announcement_prompt": 0, "assign_to_parent_at": "2022-05-24T04:17:31.000Z", "dealerLocationPhoto": null, "master_regencies_id": "3172", "consignmentPictureUrl": null, "businessCertificateUrl": "null", "isElligibleConsignment": null, "verified_microdealer_at": null, "id_card_selfie_image_url": "", "verification_microdealer": null, "businessDomicileCertificateUrl": "null"}, "catatan": "hfs", "pdf_url": "https://moladin-evo.s3.ap-southeast-1.amazonaws.com/2022/07/03/1656824863-hasil-laporan-inspeksi-19305-20220703050738.pdf", "interior": [{"key": "antena", "tab": "Audio & Sistem Alarm", "type": "radio", "label": "Antena", "value": "Lulus", "is_passed": true}, {"key": "kamera_mundur", "tab": "Audio & Sistem Alarm", "type": "radio", "label": "Kamera Mundur", "value": "Lulus", "is_passed": true}, {"key": "pemutar_audio", "tab": "Audio & Sistem Alarm", "type": "radio", "label": "Pemutar Audio", "value": "Lulus", "is_passed": true}, {"key": "alarm", "tab": "Audio & Sistem Alarm", "type": "radio", "label": "Alarm", "value": "Lulus", "is_passed": true}, {"key": "speaker", "tab": "Audio & Sistem Alarm", "type": "radio", "label": "Speaker", "value": "Lulus", "is_passed": true}, {"key": "child_lock", "tab": "Jendela & Sistem Penguncian", "type": "radio", "label": "Child Lock", "value": "Lulus", "is_passed": true}, {"key": "power_window_depan_kanan", "tab": "Jendela & Sistem Penguncian", "type": "radio", "label": "Power Window Depan Kanan", "value": "Lulus", "is_passed": true}, {"key": "power_window_depan_kiri", "tab": "Jendela & Sistem Penguncian", "type": "radio", "label": "Power Window Depan Kiri", "value": "Lulus", "is_passed": true}, {"key": "power_window_belakang_kanan", "tab": "Jendela & Sistem Penguncian", "type": "radio", "label": "Power Window Belakang Kanan", "value": "Lulus", "is_passed": true}, {"key": "power_window_belakang_kiri", "tab": "Jendela & Sistem Penguncian", "type": "radio", "label": "Power Window Belakang Kiri", "value": "Lulus", "is_passed": true}, {"key": "remote_kunci", "tab": "Jendela & Sistem Penguncian", "type": "radio", "label": "Remote Kunci", "value": "Lulus", "is_passed": true}, {"key": "power_back_door", "tab": "Jendela & Sistem Penguncian", "type": "radio", "label": "Remote Power Back Door", "value": "Lulus", "is_passed": true}, {"key": "sentral_lock", "tab": "Jendela & Sistem Penguncian", "type": "radio", "label": "Sentral Lock", "value": "Lulus", "is_passed": true}, {"key": "tombol_start_engine", "tab": "Jendela & Sistem Penguncian", "type": "radio", "label": "Tombol Start Engine", "value": "Lulus", "is_passed": true}, {"key": "dashboard", "tab": "Karpet & Cover", "type": "radio", "label": "Dashboard", "value": "Lulus", "is_passed": true}, {"key": "foto_dashboard", "tab": "Karpet & Cover", "type": "image", "label": "Foto Dashboard", "value": "https://moladin-evo.s3.ap-southeast-1.amazonaws.com/2022/06/04/1654325928-5-agya-2021-silver-metallic.jpg", "is_passed": false}, {"key": "steer", "tab": "Karpet & Cover", "type": "radio", "label": "Steer", "value": "Lulus", "is_passed": true}, {"key": "knob_transmisi", "tab": "Karpet & Cover", "type": "radio", "label": "Knob Transmisi", "value": "Lulus", "is_passed": true}, {"key": "foto_knob_transmisi", "tab": "Karpet & Cover", "type": "image", "label": "Foto Knob Transmisi", "value": "https://moladin-evo.s3.ap-southeast-1.amazonaws.com/2022/06/04/1654325931-5-agya-2021-silver-metallic.jpg", "is_passed": false}, {"key": "door_trim", "tab": "Karpet & Cover", "type": "radio", "label": "Door Trim", "value": "Lulus", "is_passed": true}, {"key": "jok_depan_kanan", "tab": "Karpet & Cover", "type": "radio", "label": "Jok Depan Kanan", "value": "Lulus", "is_passed": true}, {"key": "jok_depan_kiri", "tab": "Karpet & Cover", "type": "radio", "label": "Jok Depan Kiri", "value": "Lulus", "is_passed": true}, {"key": "jok_baris_2", "tab": "Karpet & Cover", "type": "radio", "label": "Jok Baris 2", "value": "Lulus", "is_passed": true}, {"key": "foto_jok_baris_2", "tab": "Karpet & Cover", "type": "image", "label": "Foto Jok Baris 2", "value": "https://moladin-evo.s3.ap-southeast-1.amazonaws.com/2022/06/04/1654325941-img_20220604_135853206.jpg", "is_passed": false}, {"key": "jok_baris_3", "tab": "Karpet & Cover", "type": "radio", "label": "Jok Baris 3", "value": "Lulus", "is_passed": true}, {"key": "foto_jok_baris_3", "tab": "Karpet & Cover", "type": "image", "label": "Foto Jok Baris 3", "value": "https://moladin-evo.s3.ap-southeast-1.amazonaws.com/2022/06/04/1654325944-img_20220603_102400.jpg", "is_passed": false}, {"key": "laci_dashboard", "tab": "Karpet & Cover", "type": "radio", "label": "Laci Dashboard", "value": "Lulus", "is_passed": true}, {"key": "plafond", "tab": "Karpet & Cover", "type": "radio", "label": "Plafond", "value": "Lulus", "is_passed": true}, {"key": "lighter", "tab": "Karpet & Cover", "type": "radio", "label": "Lighter", "value": "Lulus", "is_passed": true}, {"key": "elektrik_seat", "tab": "Kelengkapan Interior", "type": "radio", "label": "Elektrik Seat", "value": "Lulus", "is_passed": true}, {"key": "cruis_control", "tab": "Kelengkapan Interior", "type": "radio", "label": "Cruise Control", "value": "Lulus", "is_passed": true}, {"key": "sensor_parkir", "tab": "Kelengkapan Interior", "type": "radio", "label": "Sensor Parkir", "value": "Lulus", "is_passed": true}, {"key": "klakson", "tab": "Kelengkapan Interior", "type": "radio", "label": "Klakson", "value": "Lulus", "is_passed": true}, {"key": "kunci_steer", "tab": "Kelengkapan Interior", "type": "radio", "label": "Kunci Steer", "value": "Lulus", "is_passed": true}, {"key": "lampu_indikator", "tab": "Kelengkapan Interior", "type": "radio", "label": "Lampu Indikator", "value": "Lulus", "is_passed": true}, {"key": "navigasi", "tab": "Kelengkapan Interior", "type": "radio", "label": "Navigasi", "value": "Lulus", "is_passed": true}, {"key": "paddle_shift", "tab": "Kelengkapan Interior", "type": "radio", "label": "Paddle Shift", "value": "Lulus", "is_passed": true}, {"key": "pedal", "tab": "Kelengkapan Interior", "type": "radio", "label": "Pedal", "value": "Lulus", "is_passed": true}, {"key": "foto_pedal", "tab": "Kelengkapan Interior", "type": "image", "label": "Foto Pedal", "value": "https://moladin-evo.s3.ap-southeast-1.amazonaws.com/2022/06/04/1654325948-screenshot_2022-06-03-10-27-55-253_commoladinmoladinagentdebug.jpg", "is_passed": false}, {"key": "power_steering", "tab": "Kelengkapan Interior", "type": "radio", "label": "Power Steering", "value": "Lulus", "is_passed": true}, {"key": "speedometer", "tab": "Kelengkapan Interior", "type": "radio", "label": "Speedometer", "value": "Lulus", "is_passed": true}, {"key": "spion_tengah", "tab": "Kelengkapan Interior", "type": "radio", "label": "Spion Tengah", "value": "Lulus", "is_passed": true}, {"key": "tuas_wiper", "tab": "Kelengkapan Interior", "type": "radio", "label": "Tuas Wiper", "value": "Lulus", "is_passed": true}, {"key": "tuas_sein", "tab": "Kelengkapan Interior", "type": "radio", "label": "Tuas Sein", "value": "Lulus", "is_passed": true}, {"key": "konsol_tengah", "tab": "Kelengkapan Interior", "type": "radio", "label": "Konsol Tengah", "value": "Lulus", "is_passed": true}, {"key": "sistem_pendingin", "tab": "Kelengkapan Interior", "type": "radio", "label": "Sistem Pendingin", "value": "Lulus", "is_passed": true}, {"key": "tombol_ac", "tab": "Kelengkapan Interior", "type": "radio", "label": "Tombol AC", "value": "Lulus", "is_passed": true}, {"key": "sabuk_pengaman", "tab": "Kelengkapan Interior", "type": "radio", "label": "Sabuk Pengaman", "value": "Lulus", "is_passed": true}, {"key": "sensor_sabuk_pengaman", "tab": "Kelengkapan Interior", "type": "radio", "label": "Sensor Sabuk Pengaman", "value": "Lulus", "is_passed": true}, {"key": "convertible_top", "tab": "Kelengkapan Interior", "type": "radio", "label": "Convertible Top", "value": "Lulus", "is_passed": true}, {"key": "sunroof_moonroof", "tab": "Kelengkapan Interior", "type": "radio", "label": "Sunroof/Moonroof", "value": "Lulus", "is_passed": true}, {"key": "foto_jok_depan", "tab": "Foto", "type": "image", "label": "Foto Jok Depan", "value": "https://moladin-evo.s3.ap-southeast-1.amazonaws.com/2022/06/04/1654325952-5-agya-2021-silver-metallic.jpg", "is_passed": false}, {"key": "foto_kolong_jok", "tab": "Foto", "type": "image", "label": "Foto Kolong Jok", "value": "https://moladin-evo.s3.ap-southeast-1.amazonaws.com/2022/06/04/1654325955-screenshot_2022-06-03-10-27-55-253_commoladinmoladinagentdebug.jpg", "is_passed": false}, {"key": "foto_odo", "tab": "Foto", "type": "image", "label": "Foto Odometer", "value": "https://moladin-evo.s3.ap-southeast-1.amazonaws.com/2022/06/04/1654325958-screenshot_2022-06-03-10-27-55-253_commoladinmoladinagentdebug.jpg", "is_passed": false}], "eksterior": [{"key": "bumper_depan", "tab": "Body & Bumper", "type": "dropdown", "label": "Bumper Depan", "value": "Normal", "is_passed": true}, {"key": "bumper_belakang", "tab": "Body & Bumper", "type": "dropdown", "label": "Bumper Belakang", "value": "Normal", "is_passed": true}, {"key": "fender_depan_kanan", "tab": "Body & Bumper", "type": "dropdown", "label": "Fender Depan Kanan", "value": "Normal", "is_passed": true}, {"key": "fender_depan_kiri", "tab": "Body & Bumper", "type": "dropdown", "label": "Fender Depan Kiri", "value": "Normal", "is_passed": true}, {"key": "fender_belakang_kanan", "tab": "Body & Bumper", "type": "dropdown", "label": "Fender Belakang Kanan", "value": "Normal", "is_passed": true}, {"key": "fender_belakang_kiri", "tab": "Body & Bumper", "type": "dropdown", "label": "Fender Belakang Kiri", "value": "Diperbaiki", "is_passed": false}, {"key": "pintu_kanan", "tab": "Body & Bumper", "type": "dropdown", "label": "Pintu Kanan", "value": "Normal", "is_passed": true}, {"key": "pintu_kiri", "tab": "Body & Bumper", "type": "dropdown", "label": "Pintu Kiri", "value": "Normal", "is_passed": true}, {"key": "pintu_belakang", "tab": "Body & Bumper", "type": "dropdown", "label": "Pintu Belakang", "value": "Normal", "is_passed": true}, {"key": "keadaan_banjir", "tab": "Body & Bumper", "type": "radio", "label": "Keadaan Banjir", "value": "Lulus", "is_passed": true}, {"key": "gril_depan", "tab": "Body & Bumper", "type": "dropdown", "label": "Grill Depan", "value": "Normal", "is_passed": true}, {"key": "kap_mesin", "tab": "Body & Bumper", "type": "dropdown", "label": "Kap Mesin", "value": "Normal", "is_passed": true}, {"key": "chasis", "tab": "Body & Bumper", "type": "radio", "label": "Chasis", "value": "Lulus", "is_passed": true}, {"key": "atap_mobil", "tab": "Body & Bumper", "type": "radio", "label": "Atap Mobil", "value": "Lulus", "is_passed": true}, {"key": "nomor_rangka", "tab": "Body & Bumper", "type": "radio", "label": "No. Rangka", "value": "Lulus", "is_passed": true}, {"key": "nomor_mesin", "tab": "Body & Bumper", "type": "radio", "label": "No. Mesin", "value": "Lulus", "is_passed": true}, {"key": "tabrak_major", "tab": "Body & Bumper", "type": "radio", "label": "Tabrak Major", "value": "Lulus", "is_passed": true}, {"key": "kaca_depan", "tab": "Kaca & Spion", "type": "dropdown", "label": "Kaca Depan", "value": "Normal", "is_passed": true}, {"key": "kaca_belakang", "tab": "Kaca & Spion", "type": "dropdown", "label": "Kaca Belakang", "value": "Normal", "is_passed": true}, {"key": "kaca_kanan_depan", "tab": "Kaca & Spion", "type": "dropdown", "label": "Kaca Kanan Depan", "value": "Normal", "is_passed": true}, {"key": "kaca_kanan_belakang", "tab": "Kaca & Spion", "type": "dropdown", "label": "Kaca Kanan Belakang", "value": "Normal", "is_passed": true}, {"key": "kaca_kiri_depan", "tab": "Kaca & Spion", "type": "dropdown", "label": "Kaca Kiri Depan", "value": "Normal", "is_passed": true}, {"key": "kaca_kiri_belakang", "tab": "Kaca & Spion", "type": "dropdown", "label": "Kaca Kiri Belakang", "value": "Normal", "is_passed": true}, {"key": "spion_kanan", "tab": "Kaca & Spion", "type": "radio", "label": "Spion Kanan", "value": "Normal", "is_passed": true}, {"key": "foto_spion_kanan", "tab": "Kaca & Spion", "type": "image", "label": "Foto Spion Kanan", "value": "https://moladin-evo.s3.ap-southeast-1.amazonaws.com/2022/06/04/1654325773-img_20220604_135608992.jpg", "is_passed": false}, {"key": "spion_kiri", "tab": "Kaca & Spion", "type": "radio", "label": "Spion Kiri", "value": "Normal", "is_passed": true}, {"key": "foto_spion_kiri", "tab": "Kaca & Spion", "type": "image", "label": "Foto Spion Kiri", "value": "https://moladin-evo.s3.ap-southeast-1.amazonaws.com/2022/06/04/1654325776-screenshot_2022-06-03-10-27-55-253_commoladinmoladinagentdebug.jpg", "is_passed": false}, {"key": "wiper_depan", "tab": "Kaca & Spion", "type": "radio", "label": "Wiper Depan", "value": "Normal", "is_passed": true}, {"key": "wiper_belakang", "tab": "Kaca & Spion", "type": "radio", "label": "Wiper Belakang", "value": "Normal", "is_passed": true}, {"key": "spion_elektric_kanan", "tab": "Kaca & Spion", "type": "radio", "label": "Spion Electric Kanan", "value": "Normal", "is_passed": true}, {"key": "spion_elektric_kiri", "tab": "Kaca & Spion", "type": "radio", "label": "Spion Electric Kiri", "value": "Normal", "is_passed": true}, {"key": "lampur_otomatis_dim", "tab": "Lampu Eksterior", "type": "radio", "label": "Lampu Otomatis/Dim", "value": "Lulus", "is_passed": true}, {"key": "lampur_depan_kanan", "tab": "Lampu Eksterior", "type": "radio", "label": "Lampu Depan Kanan", "value": "Lulus", "is_passed": true}, {"key": "lampur_depan_kiri", "tab": "Lampu Eksterior", "type": "radio", "label": "Lampu Depan Kiri", "value": "Lulus", "is_passed": true}, {"key": "lampur_belakang_kanan", "tab": "Lampu Eksterior", "type": "radio", "label": "Lampu Belakang Kanan", "value": "Lulus", "is_passed": true}, {"key": "lampur_belakang_kiri", "tab": "Lampu Eksterior", "type": "radio", "label": "Lampu Belakang Kiri", "value": "Lulus", "is_passed": true}, {"key": "lampur_sein", "tab": "Lampu Eksterior", "type": "radio", "label": "Lampu Sein", "value": "Lulus", "is_passed": true}, {"key": "lampur_hazard", "tab": "Lampu Eksterior", "type": "radio", "label": "Lampu Hazard", "value": "Lulus", "is_passed": true}, {"key": "lampur_kabut", "tab": "Lampu Eksterior", "type": "radio", "label": "Lampu Kabut", "value": "Lulus", "is_passed": true}, {"key": "lampur_mundur", "tab": "Lampu Eksterior", "type": "radio", "label": "Lampu Mundur", "value": "Lulus", "is_passed": true}, {"key": "ban_depan_kanan", "tab": "Velg & Ban", "type": "radio", "label": "Ban Depan Kanan", "value": "Tebal", "is_passed": true}, {"key": "ban_depan_kiri", "tab": "Velg & Ban", "type": "radio", "label": "Ban Depan Kiri", "value": "Tebal", "is_passed": true}, {"key": "ban_belakang_kanan", "tab": "Velg & Ban", "type": "radio", "label": "Ban Belakang Kanan", "value": "Tebal", "is_passed": true}, {"key": "ban_belakang_kiri", "tab": "Velg & Ban", "type": "radio", "label": "Ban Belakang Kiri", "value": "Tebal", "is_passed": true}, {"key": "velg_depan_kanan", "tab": "Velg & Ban", "type": "radio", "label": "Velg Depan Kanan", "value": "Lulus", "is_passed": true}, {"key": "velg_depan_kiri", "tab": "Velg & Ban", "type": "radio", "label": "Velg Depan Kiri", "value": "Lulus", "is_passed": true}, {"key": "velg_belakang_kanan", "tab": "Velg & Ban", "type": "radio", "label": "Velg Belakang Kanan", "value": "Lulus", "is_passed": true}, {"key": "velg_belakang_kiri", "tab": "Velg & Ban", "type": "radio", "label": "Velg Belakang Kiri", "value": "Lulus", "is_passed": true}, {"key": "ban_serep", "tab": "Velg & Ban", "type": "radio", "label": "Ban Serep", "value": "Lulus", "is_passed": true}, {"key": "toolkit", "tab": "Velg & Ban", "type": "radio", "label": "Toolkit", "value": "Lulus", "is_passed": true}, {"key": "foto_depan", "tab": "Foto", "type": "image", "label": "Foto Depan", "value": "https://moladin-evo.s3.ap-southeast-1.amazonaws.com/2022/06/04/1654325780-5-agya-2021-silver-metallic.jpg", "is_passed": false}, {"key": "foto_kanan", "tab": "Foto", "type": "image", "label": "Foto Kanan", "value": "https://moladin-evo.s3.ap-southeast-1.amazonaws.com/2022/06/04/1654325783-img_20220603_102400.jpg", "is_passed": false}, {"key": "foto_kiri", "tab": "Foto", "type": "image", "label": "Foto Kiri", "value": "https://moladin-evo.s3.ap-southeast-1.amazonaws.com/2022/06/04/1654325785-img_20220603_102400.jpg", "is_passed": false}, {"key": "foto_belakang", "tab": "Foto", "type": "image", "label": "Foto Belakang", "value": "https://moladin-evo.s3.ap-southeast-1.amazonaws.com/2022/06/04/1654325787-img_20220603_102400.jpg", "is_passed": false}, {"key": "foto_atap", "tab": "Foto", "type": "image", "label": "Foto Atap", "value": "https://moladin-evo.s3.ap-southeast-1.amazonaws.com/2022/06/04/1654325892-img_20220604_135627131.jpg", "is_passed": false}, {"key": "foto_kolong_bumper_depan", "tab": "Foto", "type": "image", "label": "Foto Kolong Bumper Depan", "value": "https://moladin-evo.s3.ap-southeast-1.amazonaws.com/2022/06/04/1654325897-5-agya-2021-silver-metallic.jpg", "is_passed": false}, {"key": "foto_kolong_bumper_belakang", "tab": "Foto", "type": "image", "label": "Foto Kolong Bumper Belakang", "value": "https://moladin-evo.s3.ap-southeast-1.amazonaws.com/2022/06/04/1654325899-screenshot_2022-06-03-10-27-55-253_commoladinmoladinagentdebug.jpg", "is_passed": false}, {"key": "foto_mesin", "tab": "Foto", "type": "image", "label": "Foto Mesin", "value": "https://moladin-evo.s3.ap-southeast-1.amazonaws.com/2022/06/04/1654325912-5-agya-2021-silver-metallic.jpg", "is_passed": false}, {"key": "foto_kap_mesin", "tab": "Foto", "type": "image", "label": "Foto Kap Mesin", "value": "https://moladin-evo.s3.ap-southeast-1.amazonaws.com/2022/06/04/1654325920-screenshot_2022-06-03-10-23-44-218_commoladinmoladinagentdebug.jpg", "is_passed": false}, {"key": "foto_apron", "tab": "Foto", "type": "image", "label": "Foto Apron", "value": "https://moladin-evo.s3.ap-southeast-1.amazonaws.com/2022/06/04/1654325922-screenshot_2022-06-03-10-27-55-253_commoladinmoladinagentdebug.jpg", "is_passed": false}, {"key": "foto_grill_bumper", "tab": "Foto", "type": "image", "label": "Foto Grill Bumper", "value": "https://moladin-evo.s3.ap-southeast-1.amazonaws.com/2022/06/04/1654325924-screenshot_2022-06-03-10-27-55-253_commoladinmoladinagentdebug.jpg", "is_passed": false}], "productId": "19305", "tes_jalan": [{"key": "akselerasi_mesin", "tab": "Mesin", "type": "radio", "label": "Akselerasi Mesin", "value": "Normal", "is_passed": true}, {"key": "engine_idling", "tab": "Mesin", "type": "radio", "label": "Engine Idling", "value": "Normal", "is_passed": true}, {"key": "engine_starting", "tab": "Mesin", "type": "radio", "label": "Engine Starting", "value": "Normal", "is_passed": true}, {"key": "suara_mesin", "tab": "Mesin", "type": "radio", "label": "Suara Mesin", "value": "Normal", "is_passed": true}, {"key": "racksteer", "tab": "Kemudi & Rem", "type": "radio", "label": "Racksteer", "value": "Lulus", "is_passed": true}, {"key": "abs_sensor", "tab": "Kemudi & Rem", "type": "radio", "label": "ABS Sensor", "value": "Normal", "is_passed": true}, {"key": "sistem_pengereman", "tab": "Kemudi & Rem", "type": "radio", "label": "Sistem Pengereman", "value": "Normal", "is_passed": true}, {"key": "sistem_kaki_kaki", "tab": "Kemudi & Rem", "type": "radio", "label": "Suara Kaki-Kaki", "value": "Lulus", "is_passed": true}, {"key": "bunyi_perpindahan_transmisi", "tab": "Transmisi, Kopling & Roda Penggerak", "type": "radio", "label": "Bunyi Perpindahan Transmisi", "value": "Lulus", "is_passed": true}, {"key": "sistem_kopling", "tab": "Transmisi, Kopling & Roda Penggerak", "type": "radio", "label": "Sistem Kopling", "value": "Normal", "is_passed": true}, {"key": "sistem_tuas_rem", "tab": "Transmisi, Kopling & Roda Penggerak", "type": "radio", "label": "Sistem Tuas Rem", "value": "Normal", "is_passed": true}, {"key": "sistem_pedal_rem", "tab": "Transmisi, Kopling & Roda Penggerak", "type": "radio", "label": "Sistem Pedal Rem", "value": "Normal", "is_passed": true}, {"key": "perpindahan_transmisi", "tab": "Transmisi, Kopling & Roda Penggerak", "type": "radio", "label": "Perpindahan Transmisi", "value": "Lulus", "is_passed": true}], "informasi_umum": [{"key": "brand_id", "type": "dropdown", "label": "Merek", "value": "13"}, {"key": "model_id", "type": "dropdown", "label": "Model", "value": "148"}, {"key": "type_id", "type": "dropdown", "label": "Varian", "value": "833"}, {"key": "tahun", "type": "dropdown", "label": "Tahun Kendaraan", "value": "2021"}, {"key": "warna_primer_id", "type": "dropdown", "label": "Warna", "value": "1"}, {"key": "jarak_tempuh", "type": "freetext", "label": "Jarak Tempuh", "value": "22222"}, {"key": "nomor_polisi", "type": "freetext", "label": "Nomor Polisi", "value": "KT8240DEF"}, {"key": "dokumen_stnk", "type": "radio", "label": "STNK", "value": "Pribadi"}, {"key": "stnk_surat_pelepasan_hak", "type": "none", "label": "", "value": ""}, {"key": "stnk_depan", "type": "image", "label": "STNK", "value": "https://moladin-evo.s3.ap-southeast-1.amazonaws.com/2022/06/04/1654325651-screenshot_2022-06-03-10-27-55-253_commoladinmoladinagentdebug.jpg"}, {"key": "stnk_belakang", "type": "image", "label": "", "value": "https://moladin-evo.s3.ap-southeast-1.amazonaws.com/2022/06/04/1654325653-screenshot_2022-06-03-10-27-55-253_commoladinmoladinagentdebug.jpg"}, {"key": "tools_standard_dan_kunci_roda", "type": "radio", "label": "Tools Standard dan Kunci Roda", "value": "Ada"}, {"key": "ktp_sesuai_stnk_bpkb", "type": "none", "label": "Fotocopy KTP sesuai STNK dan BPKB", "value": ""}, {"key": "blanko_kwitansi_bermaterai", "type": "none", "label": "Blanko Kwitansi Bermaterai", "value": ""}, {"key": "form_a", "type": "none", "label": "Form A", "value": ""}, {"key": "dokumen_pajak", "type": "radio", "label": "Pajak", "value": "Hidup"}, {"key": "pajak", "type": "image", "label": "Foto Pajak", "value": "https://moladin-evo.s3.ap-southeast-1.amazonaws.com/2022/06/04/1654325656-screenshot_2022-06-03-10-27-55-253_commoladinmoladinagentdebug.jpg"}, {"key": "dokumen_bpkb", "type": "radio", "label": "BPKB", "value": "Leasing"}, {"key": "nomor_bpkb", "type": "none", "label": "Nomor BPKB", "value": ""}, {"key": "bpkb_halaman_1", "type": "none", "label": "Foto BPKB", "value": ""}, {"key": "bpkb_halaman_2", "type": "none", "label": "", "value": ""}, {"key": "bpkb_halaman_3", "type": "none", "label": "", "value": ""}, {"key": "dokumen_faktur", "type": "radio", "label": "Faktur", "value": "Ada"}, {"key": "faktur", "type": "image", "label": "Foto Faktur", "value": "https://moladin-evo.s3.ap-southeast-1.amazonaws.com/2022/06/04/1654325677-screenshot_2022-06-03-10-27-55-253_commoladinmoladinagentdebug.jpg"}, {"key": "dokumen_nik", "type": "radio", "label": "NIK", "value": "Ada"}, {"key": "nik", "type": "image", "label": "Foto NIK", "value": "https://moladin-evo.s3.ap-southeast-1.amazonaws.com/2022/06/04/1654325679-screenshot_2022-06-03-10-27-55-253_commoladinmoladinagentdebug.jpg"}, {"key": "dokumen_buku_manual", "type": "radio", "label": "Buku Manual", "value": "Ada"}, {"key": "buku_manual", "type": "image", "label": "Foto Buku Manual", "value": "https://moladin-evo.s3.ap-southeast-1.amazonaws.com/2022/06/04/1654325681-img_20220603_102400.jpg"}, {"key": "dokumen_buku_servis", "type": "radio", "label": "Buku Service", "value": "Ada"}, {"key": "buku_servis", "type": "image", "label": "Foto Buku Service", "value": "https://moladin-evo.s3.ap-southeast-1.amazonaws.com/2022/06/04/1654325688-img_20220603_102400.jpg"}, {"key": "dokumen_kunci_serep", "type": "radio", "label": "Kunci Serep", "value": "Ada"}, {"key": "kunci_serep", "type": "image", "label": "Foto Kunci Serep Mobil", "value": "https://moladin-evo.s3.ap-southeast-1.amazonaws.com/2022/06/04/1654325690-screenshot_2022-06-03-10-27-55-253_commoladinmoladinagentdebug.jpg"}, {"key": "jumlah_kursi", "type": "freetext", "label": "Jumlah Kursi", "value": "5"}, {"key": "nomor_rangka", "type": "freetext", "label": "Nomor Rangka", "value": "55666666"}, {"key": "nomor_mesin", "type": "freetext", "label": "Nomor Mesin", "value": "55567776"}], "nama_inspektor": "ASO Warehouse", "tanggal_inspeksi": "2022-07-03 12:07:38", "informasi_leasing": [{"key": "nama_leasing", "type": "freetext", "label": "Nama Leasing", "value": "vuju"}, {"key": "kartu_pelunasan_takeover_leasing", "type": "image", "label": "Kartu Pelunasan", "value": "https://moladin-evo.s3.ap-southeast-1.amazonaws.com/2022/06/04/1654325664-screenshot_2022-06-03-10-27-55-253_commoladinmoladinagentdebug.jpg"}, {"key": "surat_kuasa_takeover_leasing", "type": "image", "label": "Surat Kuasa", "value": "https://moladin-evo.s3.ap-southeast-1.amazonaws.com/2022/06/04/1654325666-img_20220603_102400.jpg"}, {"key": "surat_pernyataan_takeover_leasing", "type": "image", "label": "Surat Pernyataan", "value": "https://moladin-evo.s3.ap-southeast-1.amazonaws.com/2022/06/04/1654325668-img_20220603_102400.jpg"}, {"key": "nama_bank_leasing", "type": "image_text", "label": "Nama Bank Leasing", "value": "Bank BRI "}, {"key": "kode_bank_leasing", "type": "none", "label": "Kode Bank Leasing", "value": "bri"}, {"key": "nomor_rekening_leasing", "type": "validation", "label": "Rekening Leasing", "value": "111111"}, {"key": "nama_rekening_leasing", "type": "none", "label": "Nama Rekening Leasing", "value": "BRI Simulator A"}], "informasi_pemilik": [{"key": "no_wa_penjual", "type": "freetext", "label": "Nomor WhatsApp Pemilik Mobil", "value": "088888888"}, {"key": "ktp", "type": "image", "label": "KTP Pemilik Mobil", "value": "https://moladin-evo.s3.ap-southeast-1.amazonaws.com/2022/06/04/1654325636-screenshot_2022-06-03-10-27-55-253_commoladinmoladinagentdebug.jpg"}, {"key": "bank_name", "type": "image_text", "label": "Nama Bank Pemilik Mobil", "value": "Bank BRI "}, {"key": "bank_code", "type": "none", "label": "Nama Bank Pemilik Mobil", "value": "bri"}, {"key": "bank_account_number", "type": "validation", "label": "Rekening Pemilik Mobil", "value": "111111"}, {"key": "bank_account_name", "type": "none", "label": "Nama Rekening Pemilik Mobil", "value": "BRI Simulator A"}, {"key": "seller_type", "type": "dropdown", "label": "Jenis Penjual", "value": "AGENT"}], "foto_dengan_mobil_dan_agen": "https://moladin-evo.s3.ap-southeast-1.amazonaws.com/2022/06/04/1654325967-img_20220604_135920511.jpg"}',
    ready_stock: false,
    skor_inspeksi_interior: 46,
    skor_inspeksi_exterior: 47,
    skor_inspeksi_tes_jalan: 13,
    skor_inspeksi_interior_masalah: 0,
    skor_inspeksi_exterior_masalah: 1,
    skor_inspeksi_tes_jalan_masalah: 0,
    jumlah_kursi: 5,
    nomor_rangka: '55666666',
    nomor_mesin: '55567776',
    status: null,
    biaya_admin: 1500000,
    harga_jual_changed_by_aso: false,
    reference_id: null,
    paid_at: new Date('2022-07-03 05:11:41'),
    local_timezone: null,
    buyout_at: new Date('2022-07-03 05:08:09'),
    sold_at: null,
    persetujuan_finance_at: new Date('2022-07-03 05:09:20'),
    is_listed_by_aso: true,
    hide_b2c: 0,
    komisi_aso: 0,
    seller_type: 'AGENT',
    due_date_reservation: null,
    car_province_id: null,
    additional_admin_fee: 0,
    is_consignment: 0,
    is_sold: false,
    is_aging_freeze: 0,
    context_slug: '',
    submitter_id: null,
    nomor_bpkb: '',
    dokumen_ktp_sesuai_stnk_bpkb: '',
    dokumen_blanko_kwitansi: '',
    dokumen_form_a: '',
    ucr_product_states: [
      {
        id: 119637,
        product_id: 19305,
        context_name: 'pembayaran',
        state_name: 'pembayaran-selesai',
        reason: null,
        trigger_by_user_id: null,
        trigger_by_name: 'system',
        end_state: 0,
        created_at: new Date('2022-07-03 05:11:12'),
        harga_buyout: null,
        komisi_agen: null,
        payment_link: null,
        system: 0,
        harga_jual: null,
        komisi_aso: null,
        approval_responses_status: null,
      },
      {
        id: 119636,
        product_id: 19305,
        context_name: 'pembayaran',
        state_name: 'proses-pembayaran',
        reason: null,
        trigger_by_user_id: null,
        trigger_by_name: 'system',
        end_state: 0,
        created_at: new Date('2022-07-03 05:10:01'),
        harga_buyout: null,
        komisi_agen: null,
        payment_link: null,
        system: 0,
        harga_jual: null,
        komisi_aso: null,
        approval_responses_status: null,
      },
      {
        id: 119635,
        product_id: 19305,
        context_name: 'buyout',
        state_name: 'permintaan-pembayaran-buyout-diterima',
        reason: null,
        trigger_by_user_id: 5579,
        trigger_by_name: 'Bimo WM',
        end_state: 0,
        created_at: new Date('2022-07-03 05:09:58'),
        harga_buyout: null,
        komisi_agen: null,
        payment_link: null,
        system: 0,
        harga_jual: null,
        komisi_aso: null,
        approval_responses_status: null,
      },
      {
        id: 119634,
        product_id: 19305,
        context_name: 'buyout',
        state_name: 'persetujuan-finance',
        reason: null,
        trigger_by_user_id: null,
        trigger_by_name: 'system',
        end_state: 0,
        created_at: new Date('2022-07-03 05:09:20'),
        harga_buyout: null,
        komisi_agen: null,
        payment_link: null,
        system: 0,
        harga_jual: null,
        komisi_aso: null,
        approval_responses_status: null,
      },
      {
        id: 119633,
        product_id: 19305,
        context_name: 'buyout',
        state_name: 'pengajuan-harga-buyout-disetujui',
        reason: null,
        trigger_by_user_id: 235,
        trigger_by_name: 'SM Tester',
        end_state: 0,
        created_at: new Date('2022-07-03 05:09:20'),
        harga_buyout: 45000000,
        komisi_agen: 0,
        payment_link: null,
        system: 0,
        harga_jual: null,
        komisi_aso: null,
        approval_responses_status: null,
      },
      {
        id: 119632,
        product_id: 19305,
        context_name: 'buyout',
        state_name: 'pengajuan-harga-buyout',
        reason: null,
        trigger_by_user_id: 103249,
        trigger_by_name: 'ASO JakBar',
        end_state: 0,
        created_at: new Date('2022-07-03 05:08:09'),
        harga_buyout: 45000000,
        komisi_agen: 0,
        payment_link: null,
        system: 0,
        harga_jual: null,
        komisi_aso: 0,
        approval_responses_status: null,
      },
      {
        id: 119631,
        product_id: 19305,
        context_name: 'inspeksi',
        state_name: 'inspeksi-selesai',
        reason: null,
        trigger_by_user_id: 100347,
        trigger_by_name: 'ASO Warehouse',
        end_state: 0,
        created_at: new Date('2022-07-03 05:07:44'),
        harga_buyout: null,
        komisi_agen: null,
        payment_link: null,
        system: 0,
        harga_jual: null,
        komisi_aso: null,
        approval_responses_status: null,
      },
      {
        id: 119630,
        product_id: 19305,
        context_name: 'inspeksi',
        state_name: 'document-uploaded',
        reason: null,
        trigger_by_user_id: 100347,
        trigger_by_name: 'ASO Warehouse',
        end_state: 0,
        created_at: new Date('2022-07-03 05:07:44'),
        harga_buyout: null,
        komisi_agen: null,
        payment_link: null,
        system: 0,
        harga_jual: null,
        komisi_aso: null,
        approval_responses_status: null,
      },
      {
        id: 119629,
        product_id: 19305,
        context_name: 'inspeksi',
        state_name: 'menunggu-inspeksi',
        reason: null,
        trigger_by_user_id: 103249,
        trigger_by_name: 'ASO JakBar',
        end_state: 0,
        created_at: new Date('2022-07-03 05:02:51'),
        harga_buyout: null,
        komisi_agen: null,
        payment_link: null,
        system: 0,
        harga_jual: null,
        komisi_aso: 0,
        approval_responses_status: null,
      },
    ],
    ucr_brands: {
      id: 13,
      slug: 'toyota',
      name: 'TOYOTA',
      logo_url:
        'https://moladin-evo.s3.ap-southeast-1.amazonaws.com/2022/03/22/1647934709-toyota.png',
      status: 1,
      created_at: new Date(),
      updated_at: new Date(),
      priority: 9,
    },
    ucr_models: {
      id: 148,
      brand_id: 13,
      slug: 'hiace',
      name: 'HIACE',
      created_at: new Date(),
      updated_at: new Date(),
    },
    ucr_types: {
      id: 833,
      model_id: 154,
      slug: 'v-diesel-24-at-diesel',
      name: 'V Diesel',
      concat_name: 'V Diesel 2,4 AT Diesel',
      transmission: 'AT',
      cc: '2,4',
      bbm: 'Diesel',
      created_at: new Date(),
      updated_at: new Date(),
    },
  },
];

describe('Test ProductService Methods', () => {
  describe('some test', () => {
    it('should a test', function () {});
  });
});
